services:
  simod-http:
    image: nokal/simod-http:0.13.6
    build:
      context: .
      dockerfile: http.dockerfile
    depends_on:
      - mongo
      - simod-http-worker
    volumes:
      - /tmp/simod:/tmp/simod
    environment:
      - SIMOD_DEBUG=true
      - SIMOD_STORAGE_PATH=/tmp/simod
      - SIMOD_STORAGE_DISCOVERY_EXPIRATION_TIMEDELTA=604800
      - SIMOD_STORAGE_CLEANING_TIMEDELTA=300
      - SIMOD_LOGGING_LEVEL=info
      - SIMOD_MONGO_URL=mongodb://mongo:27017
      - SIMOD_MONGO_DATABASE=simod
      - SIMOD_MONGO_COLLECTION=discoveries
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: uvicorn simod_http.main:api --host=0.0.0.0 --port=8000 --workers=4 --log-level=info --proxy-headers --root-path=/api/v1
    restart: unless-stopped

  mongo:
    image: mongo:6.0.5-jammy
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    restart: unless-stopped

  simod-http-worker:
    image: nokal/simod-http-worker:0.13.6
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: worker.dockerfile
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SIMOD_MONGO_URL=mongodb://mongo:27017
      - SIMOD_MONGO_DATABASE=simod
      - SIMOD_MONGO_COLLECTION=discoveries
    volumes:
      - /tmp/simod:/tmp/simod
    command: celery --app simod_http.worker worker --loglevel info --concurrency=2 --autoscale=2,1 --events --hostname simod-http-worker
    restart: unless-stopped

  flower:
    image: mher/flower:2.0
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=amqp://guest:guest@rabbitmq:5672//
    command: celery --broker amqp://guest:guest@rabbitmq:5672// flower --port=5555 --persistent=True --url_prefix=flower
    restart: unless-stopped

  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:stable
    ports:
      - 8000:80
    volumes:
      - ./ansible/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - simod-http
    restart: unless-stopped