services:
  simod-http:
    image: <simod-http-image-name>
    depends_on:
      - mongo
      - simod-http-worker
    volumes:
      - /mnt/attached-storage/simod:/mnt/attached-storage/simod
    environment:
      - SIMOD_DEBUG=true
      - SIMOD_STORAGE_PATH=/mnt/attached-storage/simod
      - SIMOD_STORAGE_DISCOVERY_EXPIRATION_TIMEDELTA=604800
      - SIMOD_STORAGE_CLEANING_TIMEDELTA=300
      - SIMOD_LOGGING_LEVEL=info
      - SIMOD_MONGO_URL=mongodb://mongo:27017
      - SIMOD_MONGO_DATABASE=simod
      - SIMOD_MONGO_COLLECTION=discoveries
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: uvicorn simod_http.main:api --host=0.0.0.0 --port=8000 --workers=4 --log-level=info --proxy-headers --root-path=/api/v1
    restart: unless-stopped

  mongo:
    image: mongo:6.0.5-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    restart: unless-stopped

  simod-http-worker:
    image: <simod-http-worker-image-name>
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SIMOD_MONGO_URL=mongodb://mongo:27017
      - SIMOD_MONGO_DATABASE=simod
      - SIMOD_MONGO_COLLECTION=discoveries
    volumes:
      - /mnt/attached-storage/simod:/mnt/attached-storage/simod
    command: celery --app simod_http.worker worker --loglevel info --concurrency=2 --autoscale=2,1 --events --hostname simod-http-worker
    restart: unless-stopped

  flower:
    image: mher/flower:2.0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=amqp://guest:guest@rabbitmq:5672//
    command: celery --broker amqp://guest:guest@rabbitmq:5672// flower --port=5555 --basic_auth=<flower-user>:<flower-password> --persistent=True --url_prefix=flower
    restart: unless-stopped

  redis:
    image: redis:6.0-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/simod-http/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - simod-http
    restart: unless-stopped