services:
  simod-http:
    image: nokal/simod-http:0.12.0
    depends_on:
      - mongo
    volumes:
      - /tmp/simod:/tmp/simod
    ports:
      - 8000:8000
    environment:
      - SIMOD_DEBUG=true
      - WEB_CONCURRENCY=4
      - SIMOD_HTTP_HOST=0.0.0.0
      - SIMOD_HTTP_PORT=8000
      - SIMOD_HTTP_SCHEME=http
      - SIMOD_STORAGE_PATH=/tmp/simod
      - SIMOD_STORAGE_DISCOVERY_EXPIRATION_TIMEDELTA=604800
      - SIMOD_STORAGE_CLEANING_TIMEDELTA=300
      - SIMOD_LOGGING_LEVEL=info
      - SIMOD_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - SIMOD_BROKER_EXCHANGE_NAME=simod
      - SIMOD_BROKER_QUEUE_NAME=discoveries
      - SIMOD_BROKER_PENDING_ROUTING_KEY=discoveries.status.pending
      - SIMOD_MONGO_URL=mongodb://mongo:27017
      - SIMOD_MONGO_DATABASE=simod
      - SIMOD_MONGO_COLLECTION=discoveries
    restart: unless-stopped

#  rabbitmq:
#    image: rabbitmq:3.11-management-alpine
#    ports:
#      - 5672:5672
#      - 15672:15672
#    environment:
#      - RABBITMQ_DEFAULT_USER=guest
#      - RABBITMQ_DEFAULT_PASS=guest
#    healthcheck:
#      test: [ "CMD", "rabbitmqctl", "status" ]
#      interval: 5s
#      timeout: 5s
#      retries: 3
#    restart: unless-stopped

  mongo:
    image: mongo:6.0.5-jammy
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    restart: unless-stopped