services:
  locust-master:
    image: nokal/simod-http-locust-master:0.7.0
    depends_on:
      - simod-http
    ports:
      - 8089:8089
    environment:
      - SIMOD_HTTP_URL=http://simod-http:8000
    restart: unless-stopped

  locust-worker-1:
    image: nokal/simod-http-locust-worker:0.7.0
    depends_on:
      - locust-master
    environment:
      - SIMOD_HTTP_URL=http://simod-http:8000
    restart: unless-stopped

  locust-worker-2:
    image: nokal/simod-http-locust-worker:0.7.0
    depends_on:
      - locust-master
    environment:
      - SIMOD_HTTP_URL=http://simod-http:8000
    restart: unless-stopped

  locust-worker-3:
    image: nokal/simod-http-locust-worker:0.7.0
    depends_on:
      - locust-master
    environment:
      - SIMOD_HTTP_URL=http://simod-http:8000
    restart: unless-stopped

  simod-http:
    image: nokal/simod-http:0.7.0
    depends_on:
      - rabbitmq-service
      - mongodb
    volumes:
      - /tmp/simod:/tmp/simod
    ports:
      - 8000:8000
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq-service:5672
      - SIMOD_EXCHANGE_NAME=simod
      - SIMOD_PENDING_ROUTING_KEY=requests.status.pending
      - SIMOD_HTTP_PORT=8000
      - SIMOD_HTTP_STORAGE_PATH=/tmp/simod
      - SIMOD_HTTP_LOG_LEVEL=info
    restart: unless-stopped

  rabbitmq-service:
    image: rabbitmq:3.11-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped

  mongodb:
    image: mongo:6.0.5-jammy
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    restart: unless-stopped