- name: Deploy simod-http
  hosts: main
  remote_user: ubuntu
  become: true
  vars:
    deployment_dir: /srv/simod-http
    storage_dir: /mnt/attached-storage/simod
  tasks:
    - name: Install pip3
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Install Docker for Python
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
      loop:
        - docker
        - docker-compose

    - name: Copy configuration files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ deployment_dir }}/"
        mode: "0644"
      loop:
        - compose.yaml
        - nginx.conf

    - name: Create Simod directory for mounting to containers
      ansible.builtin.file:
        path: "{{ storage_dir }}"
        state: directory
        mode: "0755"

    - name: Pull updated Docker images and restart containers
      community.docker.docker_compose:
        project_src: "{{ deployment_dir }}"
        project_name: simod-http
        pull: true
        build: false
        remove_orphans: true
        remove_volumes: true
        state: present
        restarted: true
