- name: Deploy simod-http
  hosts: main
  remote_user: ubuntu
  become: true
  vars:
    deployment_dir: /srv/simod-http
    storage_dir: /mnt/attached-storage/simod
  tasks:
    - name: Create directories with wide access
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0666"
      loop:
        - "{{ deployment_dir }}"
        - "{{ storage_dir }}"

    - name: Install apt packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3-pip
        - openssl

    - name: Install Docker for Python
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
      loop:
        - docker
        - docker-compose

    - name: Generate htpasswd file from environment variables
      ansible.builtin.shell: |
        echo "{{ flower_user }}:$(openssl passwd -apr1 {{ flower_password }})" > {{ deployment_dir }}/htpasswd
      register: htpasswd
      changed_when: true

    - name: Copy configuration files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ deployment_dir }}/"
        mode: "0644"
      loop:
        - compose.yaml
        - nginx.conf

    - name: Create environment file
      ansible.builtin.template:
        src: simod-http.env.j2
        dest: "{{ deployment_dir }}/.env"
        mode: "0644"

    - name: Pull updated Docker images and restart containers
      community.docker.docker_compose:
        project_src: "{{ deployment_dir }}"
        project_name: simod-http
        pull: true
        build: false
        remove_orphans: true
        remove_volumes: true
        state: present
        restarted: true
