name: Simod HTTP

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '*.dockerfile'
      - 'simod_http/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - '*.dockerfile'
      - 'simod_http/**'
      - '.github/workflows/**'

env:
  DOCKERHUB_USERNAME: nokal
  DOCKER_SIMOD_HTTP_NAME: nokal/simod-http
  DOCKER_SIMOD_HTTP_WORKER_NAME: nokal/simod-http-worker

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    outputs:
      version: ${{ steps.versioning.outputs.version }}
      docker_image: ${{ env.DOCKER_SIMOD_HTTP_NAME }}:${{ steps.versioning.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get the version
        id: versioning
        run: |
          pip install poetry
          echo "version=$(poetry version --short)" >> "$GITHUB_OUTPUT"

      - name: Install
        run: poetry install

      - name: Test
        run: poetry run pytest

      - name: Generate requirements.txt
        run: poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: Commit requirements.txt
        id: requirements
        uses: EndBug/add-and-commit@v9
        with:
          add: requirements.txt
          author_name: 'Ihar Suvorau'
          author_email: 'ihar.suvorau@gmail.com'
          message: 'Update requirements.txt'

      - name: Assign a version tag
        run: |
          git tag ${{ steps.versioning.outputs.version }}
          git push --tags        

  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push simod-http to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_SIMOD_HTTP_NAME }}:latest,${{ env.DOCKER_SIMOD_HTTP_NAME }}:${{ needs.build.outputs.version }}
          file: http.dockerfile
          context: .
          platforms: linux/amd64,linux/arm64

      - name: Build and push simod-http-worker to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_SIMOD_HTTP_WORKER_NAME }}:latest,${{ env.DOCKER_SIMOD_HTTP_WORKER_NAME }}:${{ needs.build.outputs.version }}
          file: worker.dockerfile
          context: .
          platforms: linux/amd64,linux/arm64

#      - name: Docker Scout
#        id: docker-scout
#        uses: docker/scout-action@v0.18.1
#        with:
#          command: quickview,compare
#          image: ${{ env.DOCKER_SIMOD_HTTP_NAME }}
#          to-latest: true
#          ignore-unchanged: true
#          only-severities: critical,high
#          write-comment: true
#          github-token: ${{ secrets.GITHUB_TOKEN }}

