name: Simod HTTP

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'src/simod_http/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'src/simod_http/**'
      - '.github/workflows/**'

env:
  DOCKERHUB_USERNAME: nokal
  DOCKERHUB_REPO: nokal/simod-http

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    outputs:
      version: ${{ steps.versioning.outputs.version }}
      docker_image: ${{ env.DOCKERHUB_REPO }}:${{ steps.versioning.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get the version
        id: versioning
        run: |
          pip install poetry
          echo "version=$(poetry version --short)" >> "$GITHUB_OUTPUT"

      - name: Install
        run: poetry install

      - name: Test
        run: poetry run pytest
        env:
          SIMOD_FAKE_REQUESTS_REPOSITORY: true

      - name: Assign a version tag
        run: |
          git tag ${{ steps.versioning.outputs.version }}
          git push --tags        

  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:latest,${{ env.DOCKERHUB_REPO }}:${{ needs.build.outputs.version }}
          file: Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
